"""removed the purpose form OTP table  migration

Revision ID: 2f2ce5f963a3
Revises: 7ee663a50015
Create Date: 2026-04-16 10:41:44.533349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f2ce5f963a3'
down_revision: Union[str, Sequence[str], None] = '7ee663a50015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
