"""added the purpose to the  OTP table  migration

Revision ID: 487d60f3ee89
Revises: 2f2ce5f963a3
Create Date: 2026-04-16 10:51:33.373019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487d60f3ee89'
down_revision: Union[str, Sequence[str], None] = '2f2ce5f963a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
